/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SigninImport } from './routes/signin'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthChatImport } from './routes/_auth/_chat'
import { Route as AuthChatIndexImport } from './routes/_auth/_chat/index'
import { Route as AuthUserUseridImport } from './routes/_auth/user/$user_id'
import { Route as AuthCreateConversationImport } from './routes/_auth/create.conversation'
import { Route as AuthCallCallidImport } from './routes/_auth/call/$call_id'
import { Route as AuthChatChatidImport } from './routes/_auth/_chat/$chat_id'
import { Route as AuthChatidScheduleImport } from './routes/_auth/$chat_id.schedule'
import { Route as AuthChatChatidIndexImport } from './routes/_auth/_chat/$chat_id.index'

// Create/Update Routes

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthChatRoute = AuthChatImport.update({
  id: '/_chat',
  getParentRoute: () => AuthRoute,
} as any)

const AuthChatIndexRoute = AuthChatIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChatRoute,
} as any)

const AuthUserUseridRoute = AuthUserUseridImport.update({
  id: '/user/$user_id',
  path: '/user/$user_id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCreateConversationRoute = AuthCreateConversationImport.update({
  id: '/create/conversation',
  path: '/create/conversation',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCallCallidRoute = AuthCallCallidImport.update({
  id: '/call/$call_id',
  path: '/call/$call_id',
  getParentRoute: () => AuthRoute,
} as any)

const AuthChatChatidRoute = AuthChatChatidImport.update({
  id: '/$chat_id',
  path: '/$chat_id',
  getParentRoute: () => AuthChatRoute,
} as any)

const AuthChatidScheduleRoute = AuthChatidScheduleImport.update({
  id: '/$chat_id/schedule',
  path: '/$chat_id/schedule',
  getParentRoute: () => AuthRoute,
} as any)

const AuthChatChatidIndexRoute = AuthChatChatidIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthChatChatidRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_chat': {
      id: '/_auth/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthChatImport
      parentRoute: typeof AuthImport
    }
    '/_auth/$chat_id/schedule': {
      id: '/_auth/$chat_id/schedule'
      path: '/$chat_id/schedule'
      fullPath: '/$chat_id/schedule'
      preLoaderRoute: typeof AuthChatidScheduleImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_chat/$chat_id': {
      id: '/_auth/_chat/$chat_id'
      path: '/$chat_id'
      fullPath: '/$chat_id'
      preLoaderRoute: typeof AuthChatChatidImport
      parentRoute: typeof AuthChatImport
    }
    '/_auth/call/$call_id': {
      id: '/_auth/call/$call_id'
      path: '/call/$call_id'
      fullPath: '/call/$call_id'
      preLoaderRoute: typeof AuthCallCallidImport
      parentRoute: typeof AuthImport
    }
    '/_auth/create/conversation': {
      id: '/_auth/create/conversation'
      path: '/create/conversation'
      fullPath: '/create/conversation'
      preLoaderRoute: typeof AuthCreateConversationImport
      parentRoute: typeof AuthImport
    }
    '/_auth/user/$user_id': {
      id: '/_auth/user/$user_id'
      path: '/user/$user_id'
      fullPath: '/user/$user_id'
      preLoaderRoute: typeof AuthUserUseridImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_chat/': {
      id: '/_auth/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthChatIndexImport
      parentRoute: typeof AuthChatImport
    }
    '/_auth/_chat/$chat_id/': {
      id: '/_auth/_chat/$chat_id/'
      path: '/'
      fullPath: '/$chat_id/'
      preLoaderRoute: typeof AuthChatChatidIndexImport
      parentRoute: typeof AuthChatChatidImport
    }
  }
}

// Create and export the route tree

interface AuthChatChatidRouteChildren {
  AuthChatChatidIndexRoute: typeof AuthChatChatidIndexRoute
}

const AuthChatChatidRouteChildren: AuthChatChatidRouteChildren = {
  AuthChatChatidIndexRoute: AuthChatChatidIndexRoute,
}

const AuthChatChatidRouteWithChildren = AuthChatChatidRoute._addFileChildren(
  AuthChatChatidRouteChildren,
)

interface AuthChatRouteChildren {
  AuthChatChatidRoute: typeof AuthChatChatidRouteWithChildren
  AuthChatIndexRoute: typeof AuthChatIndexRoute
}

const AuthChatRouteChildren: AuthChatRouteChildren = {
  AuthChatChatidRoute: AuthChatChatidRouteWithChildren,
  AuthChatIndexRoute: AuthChatIndexRoute,
}

const AuthChatRouteWithChildren = AuthChatRoute._addFileChildren(
  AuthChatRouteChildren,
)

interface AuthRouteChildren {
  AuthChatRoute: typeof AuthChatRouteWithChildren
  AuthChatidScheduleRoute: typeof AuthChatidScheduleRoute
  AuthCallCallidRoute: typeof AuthCallCallidRoute
  AuthCreateConversationRoute: typeof AuthCreateConversationRoute
  AuthUserUseridRoute: typeof AuthUserUseridRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChatRoute: AuthChatRouteWithChildren,
  AuthChatidScheduleRoute: AuthChatidScheduleRoute,
  AuthCallCallidRoute: AuthCallCallidRoute,
  AuthCreateConversationRoute: AuthCreateConversationRoute,
  AuthUserUseridRoute: AuthUserUseridRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthChatRouteWithChildren
  '/login': typeof LoginRoute
  '/signin': typeof SigninRoute
  '/$chat_id/schedule': typeof AuthChatidScheduleRoute
  '/$chat_id': typeof AuthChatChatidRouteWithChildren
  '/call/$call_id': typeof AuthCallCallidRoute
  '/create/conversation': typeof AuthCreateConversationRoute
  '/user/$user_id': typeof AuthUserUseridRoute
  '/': typeof AuthChatIndexRoute
  '/$chat_id/': typeof AuthChatChatidIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signin': typeof SigninRoute
  '/$chat_id/schedule': typeof AuthChatidScheduleRoute
  '/call/$call_id': typeof AuthCallCallidRoute
  '/create/conversation': typeof AuthCreateConversationRoute
  '/user/$user_id': typeof AuthUserUseridRoute
  '/': typeof AuthChatIndexRoute
  '/$chat_id': typeof AuthChatChatidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signin': typeof SigninRoute
  '/_auth/_chat': typeof AuthChatRouteWithChildren
  '/_auth/$chat_id/schedule': typeof AuthChatidScheduleRoute
  '/_auth/_chat/$chat_id': typeof AuthChatChatidRouteWithChildren
  '/_auth/call/$call_id': typeof AuthCallCallidRoute
  '/_auth/create/conversation': typeof AuthCreateConversationRoute
  '/_auth/user/$user_id': typeof AuthUserUseridRoute
  '/_auth/_chat/': typeof AuthChatIndexRoute
  '/_auth/_chat/$chat_id/': typeof AuthChatChatidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signin'
    | '/$chat_id/schedule'
    | '/$chat_id'
    | '/call/$call_id'
    | '/create/conversation'
    | '/user/$user_id'
    | '/'
    | '/$chat_id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/signin'
    | '/$chat_id/schedule'
    | '/call/$call_id'
    | '/create/conversation'
    | '/user/$user_id'
    | '/'
    | '/$chat_id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/signin'
    | '/_auth/_chat'
    | '/_auth/$chat_id/schedule'
    | '/_auth/_chat/$chat_id'
    | '/_auth/call/$call_id'
    | '/_auth/create/conversation'
    | '/_auth/user/$user_id'
    | '/_auth/_chat/'
    | '/_auth/_chat/$chat_id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SigninRoute: typeof SigninRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SigninRoute: SigninRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/signin"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_chat",
        "/_auth/$chat_id/schedule",
        "/_auth/call/$call_id",
        "/_auth/create/conversation",
        "/_auth/user/$user_id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/_auth/_chat": {
      "filePath": "_auth/_chat.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_chat/$chat_id",
        "/_auth/_chat/"
      ]
    },
    "/_auth/$chat_id/schedule": {
      "filePath": "_auth/$chat_id.schedule.tsx",
      "parent": "/_auth"
    },
    "/_auth/_chat/$chat_id": {
      "filePath": "_auth/_chat/$chat_id.tsx",
      "parent": "/_auth/_chat",
      "children": [
        "/_auth/_chat/$chat_id/"
      ]
    },
    "/_auth/call/$call_id": {
      "filePath": "_auth/call/$call_id.tsx",
      "parent": "/_auth"
    },
    "/_auth/create/conversation": {
      "filePath": "_auth/create.conversation.tsx",
      "parent": "/_auth"
    },
    "/_auth/user/$user_id": {
      "filePath": "_auth/user/$user_id.tsx",
      "parent": "/_auth"
    },
    "/_auth/_chat/": {
      "filePath": "_auth/_chat/index.tsx",
      "parent": "/_auth/_chat"
    },
    "/_auth/_chat/$chat_id/": {
      "filePath": "_auth/_chat/$chat_id.index.tsx",
      "parent": "/_auth/_chat/$chat_id"
    }
  }
}
ROUTE_MANIFEST_END */
